CREATE TABLE IF NOT EXISTS "ident" (
	"id_ident" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"email" VARCHAR(255) NOT NULL,
	"passwd" VARCHAR(255) NOT NULL,
	"id_role" SMALLINT NOT NULL,
	"nom" VARCHAR(255) NOT NULL,
	"prenom" VARCHAR(255) NOT NULL,
	"valide" BOOLEAN NOT NULL DEFAULT true,
	"valide_id_ident" INTEGER,
	"valide_lastupdate" TIMESTAMP,
	PRIMARY KEY("id_ident")
);




CREATE TABLE IF NOT EXISTS "role" (
	"id_role" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"role" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_role")
);




CREATE TABLE IF NOT EXISTS "permission" (
	"id_role" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"page" VARCHAR(255) NOT NULL,
	"fonction" VARCHAR(255),
	"permission" BOOLEAN NOT NULL DEFAULT false,
	PRIMARY KEY("id_role", "page")
);




CREATE TABLE IF NOT EXISTS "entreprise" (
	"id_entreprise" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nom" VARCHAR(255) NOT NULL,
	"description" TEXT,
	"email" VARCHAR(255),
	"telephone" VARCHAR(30),
	"valide" BOOLEAN NOT NULL DEFAULT true,
	"valide_id_ident" INTEGER,
	"valide_lastupdate" TIMESTAMP,
	PRIMARY KEY("id_entreprise")
);




CREATE TABLE IF NOT EXISTS "evaluation" (
	"id_entreprise" INTEGER NOT NULL,
	"id_ident" INTEGER NOT NULL,
	"note" SMALLINT NOT NULL,
	PRIMARY KEY("id_entreprise", "id_ident")
);




CREATE TABLE IF NOT EXISTS "offre" (
	"id_offre" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"id_entreprise" INTEGER NOT NULL,
	"titre" VARCHAR(255) NOT NULL,
	"description" TEXT,
	"base_remuneration" NUMERIC(10,2) NOT NULL,
	"date_offre" DATE NOT NULL,
	"valide" BOOLEAN NOT NULL DEFAULT true,
	"valide_id_ident" INTEGER,
	"valide_lastupdate" TIMESTAMP,
	PRIMARY KEY("id_offre")
);




CREATE TABLE IF NOT EXISTS "competence" (
	"id_competence" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"competence" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("id_competence")
);




CREATE TABLE IF NOT EXISTS "offre_has_competence" (
	"id_offre" INTEGER NOT NULL,
	"id_competence" INTEGER NOT NULL,
	PRIMARY KEY("id_offre", "id_competence")
);




CREATE TABLE IF NOT EXISTS "wishlist" (
	"id_ident" INTEGER NOT NULL,
	"id_offre" INTEGER NOT NULL,
	PRIMARY KEY("id_ident", "id_offre")
);




CREATE TABLE IF NOT EXISTS "postule" (
	"id_ident" INTEGER NOT NULL,
	"id_offre" INTEGER NOT NULL,
	"cv" VARCHAR(255) NOT NULL,
	"lettre_motivation" VARCHAR(255) NOT NULL,
	PRIMARY KEY("id_ident", "id_offre")
);



ALTER TABLE "ident"
ADD FOREIGN KEY("id_role") REFERENCES "role"("id_role")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "permission"
ADD FOREIGN KEY("id_role") REFERENCES "role"("id_role")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "evaluation"
ADD FOREIGN KEY("id_entreprise") REFERENCES "entreprise"("id_entreprise")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "evaluation"
ADD FOREIGN KEY("id_ident") REFERENCES "ident"("id_ident")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "offre"
ADD FOREIGN KEY("id_entreprise") REFERENCES "entreprise"("id_entreprise")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "offre_has_competence"
ADD FOREIGN KEY("id_offre") REFERENCES "offre"("id_offre")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "offre_has_competence"
ADD FOREIGN KEY("id_competence") REFERENCES "competence"("id_competence")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "wishlist"
ADD FOREIGN KEY("id_ident") REFERENCES "ident"("id_ident")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "wishlist"
ADD FOREIGN KEY("id_offre") REFERENCES "offre"("id_offre")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "postule"
ADD FOREIGN KEY("id_ident") REFERENCES "ident"("id_ident")
ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE "postule"
ADD FOREIGN KEY("id_offre") REFERENCES "offre"("id_offre")
ON UPDATE RESTRICT ON DELETE RESTRICT;
